### ISSUE TITLE
Shift options in js / ts conditionals

### ISSUE THREAD

**Issue by tvedtorama** [Gruntfuggly/shifter#1]
It would be very useful to be able to reorder conditionals as well, such as:

```typescript
const theTruthAboutHorses = "a horse has lots of legs" ? false : true
```
In this case, placing the cursor on the `true` text and send it leftwards.

**Comment by Gruntfuggly** [comment]
That's probably doable - it would have to be fairly simplistic though - I would capture everything between the ? and : as the left hand group and everything between the : and next ; as the right hand group. I'll see what I can do.

**Comment by Gruntfuggly** [comment]
I did some experiments to try and implement this, but unfortunately it's too far outside the scope of the extension. The extension simply converts the current bracket scope into a comma separated list and then re-arranges it. Because the conditional isn't easy to capture, I can't shift it around. You could use a regex to match it, but it fail very easily. It probably needs a better way to detect the conditional - using a language server, or some sort of tokeniser.

**Comment by Gruntfuggly** [comment]
Looks like somebody else has created an extension to do this:

https://marketplace.visualstudio.com/items?itemName=256hz.swap-ternary
