### ISSUE TITLE
Shifting left/right removes space after comma 

### ISSUE THREAD

**Issue by zbs** [Gruntfuggly/shifter#6]
In Python, I used the feature as follows:
```callback(has_alert, node):```

With my selection in the word `node`, I use the shift left command, but it results in:                   
```callback( node,has_alert):```

**Comment by Gruntfuggly** [comment]
The extension is not very clever. The problem is that people use different formatting so it's not possible for the extension to know how to apply the spaces. What it does try to do is to call your formatter after moving the arguments around, so if you don't have a formatter for python it may not sort the spaces out.

**Comment by zbs** [comment]
Okay, that works for me for now. Thanks.
